// Sample config - DO NOT COMMIT your real keys here.
window.CONFIG = {
  GOOGLE_MAPS_API_KEY: "YOUR_GOOGLE_MAPS_KEY_HERE",
  STORMGLASS_KEY: "YOUR_STORMGLASS_KEY_HERE",
  OPENWEATHER_KEY: "YOUR_OPENWEATHER_KEY_HERE"
};
